### PR TITLE
Lps 68088

### PR DESCRIPTION
**Pull request by sherlyliu**
Hi Carlos,

There has a LPP ticket reports resource bundle sample has some issue, exception occurs when customer do redeploy, I changed the sample, CSE suggest we update sample.
https://issues.liferay.com/browse/LPP-22450

Thanks,
Sherly

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey Carlos,
Could you help to review this pull request? we have a ee customer is waiting for this fix.
Thanks,
Dale

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/sherlyliu/liferay-blade-samples/pull/1. [See changes here.](https://github.com/csierra/liferay-blade-samples/compare/83dd056~2...83dd056) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-samples/pull/113. [See changes here.](https://github.com/csierra/liferay-blade-samples/compare/511181a~1...511181a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
